name: update

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 11 * * *'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Get 
        uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Run
        run: |
          cd ${GITHUB_WORKSPACE}/src/
          go run main.go
      - name: Deploy
        run: |
          git config user.name "${{ secrets.SECRET_USER }}"
          git config user.email "${{ secrets.SECRET_USER }}@users.noreply.github.com"
          git add .
          git commit -am "update"
          git push --all -f https://${{ secrets.TOKEN }}@github.com/${{ secrets.SECRET_REPO }}.git
